# Generated by Django 4.2.30 on 2026-07-17 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='control_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plato',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plato',
            name='stock_minimo',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MovimientoPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso de Producción'), ('EGRESO', 'Egreso por Merma/Pérdida'), ('AJUSTE', 'Ajuste de Inventario'), ('VENTA', 'Venta Automática (Comanda)')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock', to='menu.plato')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movimiento_plato',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
