# Generated by Django 4.2.30 on 2026-07-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_reserva_cliente_llego_reserva_comanda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cliente_dni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI / Documento'),
        ),
    ]
