# Generated by Django 4.2.30 on 2026-07-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0006_comanda_cliente_comanda_tipo_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineacomanda',
            name='stock_descontado',
            field=models.BooleanField(default=False, help_text='Indica si ya se descontó del stock del plato'),
        ),
    ]
